"""rename columns'


Revision ID: 4540f6a4af37
Revises: 8263e3d842e7
Create Date: 2021-11-12 21:30:22.978031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4540f6a4af37'
down_revision = '8263e3d842e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checkout_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('rental', 'checked_out_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_out_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('rental', 'checkout_date')
    # ### end Alembic commands ###
