"""rename column

Revision ID: 8263e3d842e7
Revises: effaa0272372
Create Date: 2021-11-12 21:16:39.774245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8263e3d842e7'
down_revision = 'effaa0272372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_out_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('rental', 'checke_out_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checke_out_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('rental', 'checked_out_date')
    # ### end Alembic commands ###
